spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://118.190.159.10:3306/timer-user?characterEncoding=utf-8&useSSL=false
        username: root
        password: Song0120.
        type: com.alibaba.druid.pool.DruidDataSource
        filters: stat
        maxActive: 200 #最大连接数
        initialSize: 1 #初始化连接
        maxWait: 60000 #连接超时时间
        minIdle: 1     #最小连接数
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000 #最大空闲时间
     #   validationQuery: select 'x'  不用该配置性能较高
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    application:
      name: user-server
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ya.song.userserver.entity.User

eureka:
  client:
    service-url:
          defaultZone: http://yasong:yasong@localhost:8082/eureka/

server:
  port: 8083
ys:
  name: yinyasong

jwt:
  secret: secret
  expiration: 168
  notBefore: 120


mypros:
    urls:
      - /user/byId
      - /user/findUserById




