spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://118.190.159.10:3306/timer-picture?characterEncoding=utf-8&useSSL=false
        username: root
        password: Song0120.
        type: com.alibaba.druid.pool.DruidDataSource
        filters: stat
        maxActive: 200 #最大连接数
        initialSize: 1 #初始化连接
        maxWait: 60000 #连接超时时间
        minIdle: 1     #最小连接数
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000 #最大空闲时间
     #   validationQuery: select 'x'  不用该配置性能较高
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    application:
      name: picture-server
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ya.song.pictureserver.entity.Picture

eureka:
  client:
    service-url:
          defaultZone: http://localhost:8082/eureka/

server:
  port: 8084
ys:
  name: yinyasong

jwt:
  secret: secret
  expiration: 168
  notBefore: 120


mypros:
    urls:
      - /user/byId
      - /user/findUserById

storage:
  system: windows
##windows存储路径G:\studySelf\myProjectFoGit\picture-server\upload
  rootLocation: G:\\studySelf\\myProjectFoGit\\picture-server\\upload\\images
##linux存储路径
  serverLocation: /home/picture-server/upload/images
##图片请求路径
  requestLocation: /files/



